#-------------------------------
# Cài đặt trang web
title: CastroForGeorgia
logo: '/images/logo.png' # Bạn có thể thêm logo riêng. Ví dụ '/images/logo.png'.
logo_dark: '/images/logo.png'
description: Andres Castro, một nhà vô địch của nhân dân tại Khu vực Bầu cử số 5 của Georgia.
color_scheme: auto # Bạn có thể chọn ba chế độ: auto, light và dark. Theo mặc định, chế độ auto được đặt, nghĩa là người dùng có thể tự chọn chế độ sáng hoặc tối.

#-------------------------------
# Cài đặt điều hướng
menu_settings:
  menu_items:
    - title: 'Trang chủ'
      url: '/'
    - title: 'Giới thiệu'
      url: '/about/'
    - title: "Tại sao tôi ứng cử"
      url: '/blog/leadership-grounded-in-experience-why-im-running-for-congress-district05-unions-voterrights-grassroots-progressive-workingclass-atlanta-politics-castro-gapol'
    - title: 'Chính sách'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Liên hệ'
      url: 'https://actionnetwork.org/forms/connect-with-andres-share-your-vision'

#-------------------------------
# Cài đặt tác giả
author:
  author_name: Andres Castro
  author_avatar: '/images/about-me-photo-zoom.jpg'

#-------------------------------
# Cài đặt anh hùng
hero:
  enable: true
  hero_role: "Ứng cử viên Hạ viện Hoa Kỳ (GA-05) ∙ Đấu tranh cho các gia đình lao động, nhà ở giá rẻ và phẩm giá kinh tế"
  hero_title: "Chào! Tôi là Andres <img src=\"/images/about-me-photo-zoom.jpg\" alt=\"Andres Castro Picture\" loading=\"lazy\"> <br> Đấu tranh vì Khu vực 5 của Georgia"
  hero_description: "Cùng nhau, chúng ta có thể xây dựng một tương lai phục vụ mọi người — nơi công bằng, công lý và cơ hội không chỉ là lời hứa mà là hiện thực. Hãy tạo ra sự thay đổi ý nghĩa cho các gia đình lao động ở Georgia."
  hero_button_text: "Tham gia phong trào"
  hero_button_link: "https://actionnetwork.org/forms/connect-with-andres-share-your-vision"

#-------------------------------
# Cài đặt phần dự án
projects:
  enable: true
  projects_title: Chính sách
  projects_description: Khám phá tầm nhìn của chúng ta về một khu vực 5 Georgia công bằng hơn, công bằng hơn. Cùng nhau, chúng ta sẽ xây dựng một tương lai thịnh vượng và bình đẳng.

#-------------------------------
# Cài đặt phần Blog
blog:
  enable: true
  blog_title: Blog
  blog_description: Hãy cùng xây dựng một tương lai phục vụ tất cả chúng ta.

#-------------------------------
# Cài đặt phần Giới thiệu
about:
  enable: true
  about_image: "/images/about-me-photo.jpg"
  about_title: "Cùng nhau thay đổi"
  about_description: "Hãy xây dựng một tương lai nơi mọi gia đình ở Khu vực 5 của Georgia có quyền tiếp cận cơ hội, công bằng và công lý. Tham gia cùng tôi trong việc đấu tranh cho các giải pháp táo bạo giúp nâng cao các gia đình lao động, bảo vệ quyền dân sự và tạo ra một chính phủ thực sự phục vụ tất cả chúng ta."

#-------------------------------
# Cài đặt phần Hỏi đáp (FAQ)
faq:
  enable: true
  faq_title: "Cần câu trả lời?"
  faq_description: "Tìm hiểu về Andres Castro và cam kết của ông trong việc tạo ra một cộng đồng công bằng và bao trùm hơn tại Khu vực Bầu cử số 5 của Georgia."
  faq_items:
    - title: "Điều gì thúc đẩy Andres Castro ứng cử?"
      description: "Andres Castro đã được thúc đẩy ứng cử bởi sự thất vọng với ban lãnh đạo Đảng Dân chủ hiện tại, những người mà ông tin rằng đã ngừng ưu tiên nhu cầu của người dân. Ông thấy các nhà lãnh đạo không sẵn lòng lắng nghe, chậm chạp hành động và thỏa hiệp với những lời hứa dành cho các gia đình lao động. Andres bước lên để mang lại sự lãnh đạo táo bạo, không thỏa hiệp, đặt cư dân của Khu vực Bầu cử số 5 của Georgia lên hàng đầu."

    - title: "Andres Castro là ai?"
      description: "Andres Castro là một người con tự hào của khu vực Metro Atlanta, với gốc rễ sâu tại Marietta, Powder Springs và Atlanta. Lớn lên trong nghèo khó, ông đã học được những khó khăn của các gia đình lao động. Thông qua sự quyết tâm và làm việc chăm chỉ, Andres trở thành một Kỹ sư Phần mềm Chính, nơi ông rèn luyện chuyên môn trong việc sử dụng công nghệ để giải quyết các vấn đề phức tạp. Bây giờ, với tư cách là một ứng cử viên cho Hạ viện Hoa Kỳ tại Khu vực Bầu cử số 5 của Georgia, Andres tập trung vào việc tạo ra các giải pháp cho nhà ở giá rẻ, công bằng kinh tế và quản trị minh bạch, đảm bảo cơ hội và công bằng cho tất cả mọi người."

    - title: "Những ưu tiên chính sách chính của Andres Castro là gì?"
      description: "Các ưu tiên của Andres Castro bao gồm các giải pháp táo bạo để giải quyết bất bình đẳng hệ thống: nhà ở giá rẻ thông qua các chương trình như The Workers’ Housing Guarantee, chăm sóc sức khỏe toàn dân để đảm bảo quyền tiếp cận cho tất cả, các chương trình đào tạo lại kỹ năng công việc phù hợp với tự động hóa, và trách nhiệm của doanh nghiệp để buộc các doanh nghiệp lớn tuân thủ tiêu chuẩn tiền lương và thuế công bằng. Với nền tảng kỹ thuật, Andres cũng ủng hộ trí tuệ nhân tạo đạo đức và các giải pháp đổi mới, công bằng để tăng cường sức mạnh cho người lao động và cộng đồng."

    - title: "Làm thế nào những người ủng hộ có thể tham gia chiến dịch của Andres Castro?"
      description: "Những người ủng hộ có thể tham gia bằng cách tình nguyện vận động, gọi điện, tổ chức sự kiện, tham dự các buổi họp thị trấn và cộng đồng, và chia sẻ thông điệp chiến dịch trên các nền tảng mạng xã hội. Bạn cũng có thể đăng ký nhận bản tin của chiến dịch để cập nhật và hành động. Sự hỗ trợ và tham gia của bạn rất quan trọng để thúc đẩy sự thay đổi ý nghĩa cho Khu vực Bầu cử số 5 của Georgia."

#-------------------------------
# Liên kết mạng xã hội
social:
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/castroforgeorgia/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/CastroForGeorgia"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/castroforgeorgia.bsky.social"}
- {icon: "fa-brands fa-huggingface", name: "Huggingface", link: "https://huggingface.co/CastroForGeorgia"}

# Ví dụ về thêm một liên kết mới vào footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Các biểu tượng khác có thể được tìm thấy tại https://fontawesome.com/icons

#-------------------------------
# Google Analytics
google-analytics: G-8XLD5HNY8Q
