#-------------------------------
# Cài đặt Trang web
title: CastroForGeorgia
logo: '/images/logo.png' # Bạn có thể thêm logo riêng của mình. Ví dụ: '/images/logo.png'.
logo_dark: '/images/logo.png'
description: Andres Castro, một người đấu tranh cho quyền lợi của người dân tại Khu vực Quốc hội thứ 5 của Georgia.
color_scheme: auto # Bạn có thể chọn ba chế độ: tự động, sáng và tối. Mặc định, chế độ tự động được thiết lập, có nghĩa là người dùng có thể tự chọn chế độ sáng hoặc tối.

#-------------------------------
# Cài đặt Điều hướng
menu_settings:
  menu_items:
    - title: 'Trang chủ'
      url: '/'
    - title: 'Giới thiệu'
      url: '/about/'
    - title: "Tại sao tôi ra ứng cử"
      url: '/blog/why-im-running'
    - title: 'Chính sách'
      url: '/projects/'
    - title: 'Liên hệ'
      url: 'https://actionnetwork.org/forms/connect-with-andres-share-your-vision'

#-------------------------------
# Cài đặt Tác giả
author:
  author_name: Andres Castro
  author_avatar: '/images/about-me-photo-zoom.jpg'

#-------------------------------
# Cài đặt Hero
hero:
  enable: true
  hero_role: "Ứng cử viên Quốc hội Hoa Kỳ (GA-05) ∙ Đấu tranh cho các gia đình lao động, nhà ở giá cả phải chăng và phẩm giá kinh tế"
  hero_title: "Chào! Tôi là Andres <br> Đấu tranh cho Khu vực thứ 5 của Georgia"
  hero_description: "Cùng nhau, chúng ta có thể xây dựng một tương lai hoạt động cho tất cả mọi người—nơi công bằng, công lý và cơ hội không chỉ là những lời hứa, mà là thực tế. Hãy cùng nhau tạo ra sự thay đổi có ý nghĩa cho các gia đình lao động của Georgia."
  hero_button_text: "Tham gia phong trào"
  hero_button_link: "https://actionnetwork.org/forms/connect-with-andres-share-your-vision"

#-------------------------------
# Cài đặt Phần Dự án
projects:
  enable: true
  projects_title: Chính sách
  projects_description: Khám phá tầm nhìn của chúng tôi cho một Khu vực thứ 5 công bằng và công lý hơn của Georgia. Cùng nhau, chúng ta sẽ xây dựng một tương lai thịnh vượng và công bằng.

#-------------------------------
# Cài đặt Phần Blog
blog:
  enable: true
  blog_title: Blog
  blog_description: Hãy cùng nhau xây dựng một tương lai hoạt động cho tất cả chúng ta.

#-------------------------------
# Cài đặt Phần Giới thiệu
about:
  enable: true
  about_image: "/images/about-me-photo.jpg"
  about_title: "Cùng nhau vì sự thay đổi"
  about_description: "Hãy xây dựng một tương lai mà mỗi gia đình ở Khu vực thứ 5 của Georgia đều có cơ hội, công bằng và công lý. Hãy tham gia cùng tôi trong cuộc chiến vì những giải pháp táo bạo nhằm nâng cao các gia đình lao động, bảo vệ quyền công dân và tạo ra một chính phủ thực sự phục vụ cho tất cả chúng ta."

#-------------------------------
# Cài đặt Câu hỏi Thường gặp (FAQ)
faq:
  enable: true
  faq_title: "Cần một số câu trả lời?"
  faq_description: "Hãy tìm hiểu về Andres Castro và cam kết của anh ấy trong việc tạo ra một cộng đồng công bằng và bao trùm hơn tại Khu vực Quốc hội thứ 5 của Georgia."
  faq_items:
    - title: "Điều gì đã thúc đẩy Andres Castro ra ứng cử?"
      description: "Andres Castro ra ứng cử vì sự thất vọng với lãnh đạo Đảng Dân chủ hiện tại, mà anh tin rằng đã ngừng ưu tiên nhu cầu của người dân. Anh thấy những nhà lãnh đạo không sẵn sàng lắng nghe, chậm hành động và thỏa hiệp với những lời hứa đã đưa ra cho các gia đình lao động. Andres đang đứng lên để cung cấp một sự lãnh đạo táo bạo, không thỏa hiệp, đặt lợi ích của cư dân Khu vực Quốc hội thứ 5 của Georgia lên hàng đầu."

    - title: "Andres Castro là ai?"
      description: "Andres Castro là một người con tự hào của Metro Atlanta, có nguồn gốc sâu sắc ở Marietta, Powder Springs và Atlanta. Lớn lên trong cảnh nghèo khó, anh đã hiểu rõ những khó khăn của các gia đình lao động. Nhờ sự quyết tâm và làm việc chăm chỉ, Andres đã trở thành Kỹ sư Phần mềm Nhân viên, nơi anh đã rèn giũa chuyên môn của mình trong việc sử dụng công nghệ để giải quyết các vấn đề phức tạp. Giờ đây, với tư cách là ứng cử viên cho Đại diện Quốc hội Hoa Kỳ tại Khu vực thứ 5 của Georgia, Andres tập trung vào việc tạo ra các giải pháp cho nhà ở giá cả phải chăng, công lý kinh tế và quản trị minh bạch, đảm bảo cơ hội và công bằng cho tất cả mọi người."

    - title: "Các ưu tiên chính sách của Andres Castro là gì?"
      description: "Các ưu tiên của Andres Castro bao gồm những giải pháp táo bạo để giải quyết các bất bình đẳng hệ thống: nhà ở giá cả phải chăng thông qua các chương trình như Đảm bảo Nhà ở cho Người lao động, chăm sóc sức khỏe toàn cầu để đảm bảo mọi người đều có quyền truy cập, các chương trình đào tạo lại nghề nghiệp nhận thức về tự động hóa, và trách nhiệm của doanh nghiệp để giữ cho các doanh nghiệp lớn tuân thủ tiêu chuẩn lương và thuế công bằng. Với nền tảng kỹ thuật của mình, Andres cũng ủng hộ AI đạo đức và các giải pháp sáng tạo, công bằng để trao quyền cho người lao động và cộng đồng."

    - title: "Làm thế nào để những người ủng hộ có thể tham gia vào chiến dịch của Andres Castro?"
      description: "Những người ủng hộ có thể tham gia bằng cách tình nguyện cho việc phát động, gọi điện và tổ chức sự kiện, tham dự các cuộc họp thị trấn và cộng đồng, và chia sẻ thông điệp chiến dịch trên các nền tảng mạng xã hội. Bạn cũng có thể đăng ký nhận bản tin của chiến dịch để cập nhật thông tin và hành động. Sự ủng hộ và tham gia của bạn là rất quan trọng để thúc đẩy sự thay đổi có ý nghĩa cho Khu vực Quốc hội thứ 5 của Georgia."

#-------------------------------
# Liên kết Xã hội
social:
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/castroforgeorgia/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/CastroForGeorgia"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/castroforgeorgia.bsky.social"}
- {icon: "fa-brands fa-huggingface", name: "Huggingface", link: "https://huggingface.co/CastroForGeorgia"}

# Ví dụ về việc thêm một liên kết mới vào chân trang - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Các biểu tượng khác có thể được tìm thấy tại https://fontawesome.com/icons

#-------------------------------
# Google Analytics
google-analytics: G-8XLD5HNY8Q

#-------------------------------
# Cài đặt Địa phương hóa
languages:
  default: "en"
  supported:
  - lang_code: en
    lang_name: "Tiếng Anh (Mỹ)"
  - lang_code: es
    lang_name: "Tiếng Tây Ban Nha (MX)"
  - lang_code: vi
    lang_name: "Tiếng Việt (VN)"
  - lang_code: ko
    lang_name: "Tiếng Hàn (KR)"